/**
 * Zone naming as selection.
 *
 * A zone's name is a label for a file cluster, and every good label is
 * already lying around: the package the files belong to, the directory most
 * of them share, the archetype most of them are. So the candidates are
 * generated by code and Jev picks one — a Choice with a `none` — instead of a
 * text model inventing a title and the pipeline hoping two batches invent the
 * same one. Merging is the same move: pairs the import graph suggests might
 * be one concept are put to a Noul, replacing the string-equality merge that
 * only ever worked when the invented names happened to coincide.
 *
 * Generation is kept for the case selection cannot handle — `none`, or a
 * Choice too spread to trust — and its output goes back through Jev: a
 * Choice among the proposed names and a Noul that the winner actually
 * describes the files. That is the cascade in miniature: judge, escalate
 * with more room, verify.
 *
 * @module sourcevision/analyzers/zone-naming
 */

import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import type { Finding, Zone, ZoneCrossing, TokenUsage } from "../schema/index.js";
import { callClaude, ClaudeClientError, getJudgmentRoute } from "./claude-client.js";
import { askJev, choice, noul } from "./jev-client.js";
import type { JevQuestion, JsonValue } from "./jev-client.js";
import { tryParseJSON, mergeZonesByName } from "./enrich-parsing.js";

/**
 * kebab-or-snake segment → Title Case. Mirrors zones.ts `deriveZoneName`
 * without importing it (zones → cascade → naming → zones would be a cycle).
 * Exported so the cascade can tell an algorithmic default from a chosen name.
 */
export function algorithmicZoneName(id: string): string {
  return id
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

// ── Thresholds ───────────────────────────────────────────────────────────────

/** A naming Choice below this confidence is escalated to generated candidates. */
export const NAMING_MIN_CONFIDENCE = 0.5;
/** A pair Noul at or above this merges the two zones. */
export const MERGE_MIN_PROBABILITY = 0.8;
/** Between these a pair is reported as a low-confidence observation for a human. */
export const MERGE_UNCERTAIN_BAND: [number, number] = [0.4, 0.6];
/** A generated name must clear this on the describes-these-files Noul. */
export const GENERATED_NAME_MIN_PROBABILITY = 0.6;
/** Pair prefilter: crossings between two zones as a share of the smaller zone's edges. */
const PAIR_CROSSING_SHARE = 0.2;
const PAIR_CROSSING_MIN = 3;
const ZONE_FILE_SAMPLE = 30;
const ZONES_PER_REQUEST = 40;
const NONE = "none";

// ── Candidates ───────────────────────────────────────────────────────────────

export type CandidateSource = "package" | "directory" | "directories" | "archetype";

export interface NameCandidate {
  name: string;
  source: CandidateSource;
  /** Why this label fits, for the Choice criteria. */
  why: string;
}

/** Plural nouns for the archetype-majority candidate. */
const ARCHETYPE_NOUNS: Record<string, string> = {
  entrypoint: "Entry Points",
  utility: "Utilities",
  types: "Types",
  service: "Services",
  "cli-command": "CLI Commands",
  "route-handler": "Route Handlers",
  component: "Components",
  hook: "Hooks",
  page: "Pages",
  store: "Stores",
  middleware: "Middleware",
  schema: "Schemas",
  config: "Configuration",
  gateway: "Gateways",
  model: "Models",
  "test-helper": "Test Helpers",
};

/** Share of classified files one archetype must hold to name the zone after it. */
const ARCHETYPE_MAJORITY = 0.4;

/** Directory segments that say nothing about purpose. */
const GENERIC_SEGMENTS = new Set(["src", "lib", "app", "packages", "internal", "pkg", "source"]);

function titleCase(segment: string): string {
  return algorithmicZoneName(segment.toLowerCase().replace(/_/g, "-"));
}

/** Directory counts at a given depth, generic prefixes skipped. */
function directoryCounts(files: string[], depth: number): Map<string, number> {
  const counts = new Map<string, number>();
  for (const f of files) {
    const parts = dirname(f).split("/").filter((p) => p !== "." && p !== "");
    const meaningful = parts.filter((p) => !GENERIC_SEGMENTS.has(p.toLowerCase()));
    if (meaningful.length < depth) continue;
    const key = meaningful.slice(0, depth).join("/");
    counts.set(key, (counts.get(key) ?? 0) + 1);
  }
  return counts;
}

function top<K>(counts: Map<K, number>): [K, number] | undefined {
  return [...counts.entries()].sort((a, b) => b[1] - a[1])[0];
}

/** Name from the nearest package.json above the zone's dominant directory. */
function packageName(zone: Zone, projectDir: string | undefined): string | undefined {
  if (!projectDir) return undefined;
  const dominant = top(directoryCounts(zone.files, 1));
  if (!dominant) return undefined;
  // Walk from the deepest common directory of the dominant files upward.
  const rawDirs = zone.files.map((f) => dirname(f)).filter((d) => d !== ".");
  let dir = rawDirs.find((d) => d.split("/").some((p) => p.toLowerCase() === dominant[0].split("/")[0].toLowerCase())) ?? rawDirs[0];
  while (dir && dir !== ".") {
    const pkg = join(projectDir, dir, "package.json");
    if (existsSync(pkg)) {
      try {
        const parsed = JSON.parse(readFileSync(pkg, "utf-8")) as { name?: string };
        if (typeof parsed.name === "string" && parsed.name) {
          // Zone must actually be that package: most of its files sit under it.
          const under = zone.files.filter((f) => f.startsWith(dir + "/")).length;
          if (under / zone.files.length >= 0.6) return parsed.name.replace(/^@[^/]+\//, "");
        }
      } catch {
        // unreadable package.json → no candidate
      }
      return undefined;
    }
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return undefined;
}

export interface NamingContext {
  projectDir?: string;
  fileArchetypes?: Map<string, string | null>;
  crossings: ZoneCrossing[];
  /**
   * Zones whose generated-name fallback was already tried on this exact file
   * set and did not stick. The Jev Choice still runs (it is cached); the
   * text-model calls do not, until the zone's files change.
   */
  skipGeneratedNames?: Set<string>;
  /**
   * Do not call the text model at all; zones that would have been escalated
   * are reported in `fallbackZoneIds` for a later `sv narrate` to name.
   */
  deferGeneratedNames?: boolean;
}

/** Zones per name-proposal prompt; the answer is a map keyed by zone id. */
const NAME_PROPOSAL_CHUNK = 20;

/** Deterministic name candidates for a zone, deduplicated by name. */
export function buildNameCandidates(zone: Zone, ctx: NamingContext): NameCandidate[] {
  const out: NameCandidate[] = [];
  const seen = new Set<string>();
  const add = (c: NameCandidate) => {
    const key = c.name.toLowerCase();
    if (!c.name || seen.has(key)) return;
    seen.add(key);
    out.push(c);
  };

  const pkg = packageName(zone, ctx.projectDir);
  if (pkg) add({ name: titleCase(pkg), source: "package", why: `The files belong to the "${pkg}" package.` });

  const dir1 = top(directoryCounts(zone.files, 1));
  if (dir1) {
    add({ name: titleCase(dir1[0]), source: "directory", why: `${dir1[1]} of ${zone.files.length} files sit under ${dir1[0]}/.` });
  }
  const dir2 = top(directoryCounts(zone.files, 2));
  if (dir2 && dir2[1] >= Math.max(2, zone.files.length * 0.5)) {
    const [a, b] = dir2[0].split("/");
    add({ name: `${titleCase(a)} ${titleCase(b)}`, source: "directories", why: `${dir2[1]} files sit under ${dir2[0]}/.` });
  }

  if (ctx.fileArchetypes) {
    const counts = new Map<string, number>();
    let classified = 0;
    for (const f of zone.files) {
      const a = ctx.fileArchetypes.get(f);
      if (!a) continue;
      classified++;
      counts.set(a, (counts.get(a) ?? 0) + 1);
    }
    const majority = top(counts);
    if (majority && classified > 0 && majority[1] / classified >= ARCHETYPE_MAJORITY) {
      const noun = ARCHETYPE_NOUNS[majority[0]] ?? algorithmicZoneName(majority[0]);
      const prefix = dir1 ? titleCase(dir1[0].split("/")[0]) : "";
      const name = prefix && !noun.toLowerCase().startsWith(prefix.toLowerCase()) ? `${prefix} ${noun}` : noun;
      add({ name, source: "archetype", why: `${majority[1]} of ${classified} classified files are ${majority[0]} files.` });
    }
  }
  return out;
}

/** A description from facts: size, what the files are, where they connect. */
export function describeZoneFromFacts(zone: Zone, ctx: NamingContext, zonesById: Map<string, Zone>): string {
  const parts: string[] = [`${zone.files.length} file${zone.files.length === 1 ? "" : "s"}`];

  if (ctx.fileArchetypes) {
    const counts = new Map<string, number>();
    for (const f of zone.files) {
      const a = ctx.fileArchetypes.get(f);
      if (a) counts.set(a, (counts.get(a) ?? 0) + 1);
    }
    const nouns = [...counts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 2)
      .map(([a]) => (ARCHETYPE_NOUNS[a] ?? algorithmicZoneName(a)).toLowerCase());
    if (nouns.length > 0) parts[0] += `, mostly ${nouns.join(" and ")}`;
  }
  if (zone.entryPoints.length > 0) {
    parts.push(`entry points ${zone.entryPoints.slice(0, 3).map((f) => f.split("/").pop()).join(", ")}`);
  }
  const out = new Map<string, number>();
  const inn = new Map<string, number>();
  for (const c of ctx.crossings) {
    if (c.fromZone === zone.id) out.set(c.toZone, (out.get(c.toZone) ?? 0) + 1);
    if (c.toZone === zone.id) inn.set(c.fromZone, (inn.get(c.fromZone) ?? 0) + 1);
  }
  const label = (id: string) => zonesById.get(id)?.name ?? id;
  const topOut = [...out.entries()].sort((a, b) => b[1] - a[1]).slice(0, 2).map(([z]) => label(z));
  const topIn = [...inn.entries()].sort((a, b) => b[1] - a[1]).slice(0, 2).map(([z]) => label(z));
  if (topOut.length > 0) parts.push(`imports ${topOut.join(" and ")}`);
  if (topIn.length > 0) parts.push(`imported by ${topIn.join(" and ")}`);
  return parts.join("; ") + ".";
}

// ── Request ──────────────────────────────────────────────────────────────────

export interface ZoneNamingRequest {
  state: JsonValue;
  questions: Record<string, JevQuestion>;
  /** naming question id → zone and its candidates, in criteria order. */
  naming: Map<string, { zone: Zone; candidates: NameCandidate[] }>;
  /** pair question id → the two zones. */
  pairs: Map<string, [Zone, Zone]>;
}

/** Zone pairs the graph suggests might be one concept. */
export function candidatePairs(zones: Zone[], crossings: ZoneCrossing[]): [Zone, Zone][] {
  const edges = new Map<string, number>();
  const degree = new Map<string, number>();
  for (const c of crossings) {
    const key = [c.fromZone, c.toZone].sort().join("\u0000");
    edges.set(key, (edges.get(key) ?? 0) + 1);
    degree.set(c.fromZone, (degree.get(c.fromZone) ?? 0) + 1);
    degree.set(c.toZone, (degree.get(c.toZone) ?? 0) + 1);
  }
  const prefix = (z: Zone) => top(directoryCounts(z.files, 2))?.[0];
  const pairs: [Zone, Zone][] = [];
  for (let i = 0; i < zones.length; i++) {
    for (let j = i + 1; j < zones.length; j++) {
      const a = zones[i], b = zones[j];
      const shared = edges.get([a.id, b.id].sort().join("\u0000")) ?? 0;
      const smaller = Math.min(degree.get(a.id) ?? 0, degree.get(b.id) ?? 0);
      const dense = shared >= PAIR_CROSSING_MIN && smaller > 0 && shared / smaller >= PAIR_CROSSING_SHARE;
      const pa = prefix(a), pb = prefix(b);
      const samePrefix = pa !== undefined && pa === pb;
      if (dense || samePrefix) pairs.push([a, b]);
    }
  }
  return pairs;
}

export function buildZoneNamingRequest(zones: Zone[], ctx: NamingContext, pairs: [Zone, Zone][]): ZoneNamingRequest {
  const zState: Record<string, JsonValue> = {};
  const questions: Record<string, JevQuestion> = {};
  const naming = new Map<string, { zone: Zone; candidates: NameCandidate[] }>();
  const pairMap = new Map<string, [Zone, Zone]>();
  const idOf = new Map<string, string>();

  zones.forEach((zone, i) => {
    const id = `z${i}`;
    idOf.set(zone.id, id);
    const dirs = [...directoryCounts(zone.files, 1).entries()].sort((a, b) => b[1] - a[1]).slice(0, 3);
    const archetypes: Record<string, number> = {};
    for (const f of zone.files) {
      const a = ctx.fileArchetypes?.get(f);
      if (a) archetypes[a] = (archetypes[a] ?? 0) + 1;
    }
    zState[id] = {
      fileCount: zone.files.length,
      files: zone.files.slice(0, ZONE_FILE_SAMPLE),
      directories: Object.fromEntries(dirs),
      archetypes,
      entryPoints: zone.entryPoints.slice(0, 5),
    };
    const candidates = buildNameCandidates(zone, ctx);
    if (candidates.length > 0) {
      const criteria: Record<string, JsonValue> = {};
      candidates.forEach((c, k) => { criteria[`n${k}`] = { name: c.name, why: c.why }; });
      criteria[NONE] = "None of these is how a maintainer would refer to this group of files.";
      questions[`name-${id}`] = choice(
        `Which candidate is the name a maintainer would use for the module described by \`zones.${id}\`?`,
        criteria,
      );
      naming.set(`name-${id}`, { zone, candidates });
    }
  });

  pairs.forEach(([a, b], k) => {
    const qa = idOf.get(a.id), qb = idOf.get(b.id);
    if (!qa || !qb) return;
    const qid = `pair-${k}`;
    questions[qid] = noul(
      `Are \`zones.${qa}\` and \`zones.${qb}\` the same architectural concept — files a maintainer would keep in one module rather than two?`,
    );
    pairMap.set(qid, [a, b]);
  });

  return { state: { zones: zState }, questions, naming, pairs: pairMap };
}

// ── Generated fallback ───────────────────────────────────────────────────────

/**
 * Ask the text model for three names per zone, all zones in one prompt. The
 * answer is a map keyed by zone id; a zone missing from it gets no names.
 * Returns an empty map on any client failure.
 */
export async function proposeZoneNamesFor(zones: Zone[]): Promise<Map<string, string[]>> {
  const out = new Map<string, string[]>();
  if (zones.length === 0) return out;
  const blocks = zones.map((z) =>
    `Zone "${z.id}" (${z.files.length} files):\n${z.files.slice(0, ZONE_FILE_SAMPLE).map((f) => `  ${f}`).join("\n")}`,
  ).join("\n\n");
  const prompt = [
    `Propose three short Title Case names (2–4 words) for each of these ${zones.length} code modules. Name what the files do, not where they are.`,
    "",
    blocks,
    "",
    `Respond with ONLY a JSON object keyed by zone id, three strings per zone: {"${zones[0].id}":["Name One","Name Two","Name Three"]}`,
  ].join("\n");
  let text: string;
  try {
    ({ text } = await callClaude(prompt, undefined, { taskClass: "zone.enrich-scan" }));
  } catch (err) {
    if (err instanceof ClaudeClientError) return out;
    throw err;
  }
  const parsed = tryParseJSON(text);
  if (!parsed || typeof parsed !== "object") return out;
  for (const z of zones) {
    const arr = (parsed as Record<string, unknown>)[z.id];
    if (!Array.isArray(arr)) continue;
    const names = arr.filter((n: unknown): n is string => typeof n === "string" && n.trim().length > 0).slice(0, 3);
    if (names.length > 0) out.set(z.id, names);
  }
  return out;
}

/** Single-zone form, kept for callers that have one zone in hand. */
export async function proposeZoneNames(zone: Zone): Promise<string[]> {
  return (await proposeZoneNamesFor([zone])).get(zone.id) ?? [];
}

// ── Orchestration ────────────────────────────────────────────────────────────

export interface ZoneNamingResult {
  zones: Zone[];
  /** Pair judgments in the uncertain band, surfaced for a human. */
  findings: Finding[];
  tokenUsage?: TokenUsage;
  calls: number;
  renamed: number;
  merged: number;
  /** Zones sent to the generative fallback. */
  escalated: number;
  /** Zones that would have been escalated but were tried on the same files before. */
  skippedFallback: number;
  /** Zones whose Choice came back none/unsure and that were not skipped — the fallback's input. */
  fallbackZoneIds: string[];
}

function addUsage(total: TokenUsage, more?: TokenUsage): void {
  if (!more) return;
  total.input += more.input;
  total.output += more.output;
}

/**
 * Name (and where warranted merge) zones by selection. Inert without a
 * `zone.judge` route: returns the zones untouched.
 */
export async function nameZonesBySelection(zones: Zone[], ctx: NamingContext): Promise<ZoneNamingResult> {
  const result: ZoneNamingResult = { zones, findings: [], calls: 0, renamed: 0, merged: 0, escalated: 0, skippedFallback: 0, fallbackZoneIds: [] };
  if (zones.length === 0 || getJudgmentRoute("zone.judge") !== "typesafe") return result;

  const usage: TokenUsage = { input: 0, output: 0 };
  const named = new Map<string, string>(); // zone.id → chosen name
  const escalate: Zone[] = [];
  const mergeNames = new Map<string, string>(); // zone.id → shared name for mergeZonesByName
  const pairs = candidatePairs(zones, ctx.crossings);

  for (let start = 0; start < zones.length; start += ZONES_PER_REQUEST) {
    const batch = zones.slice(start, start + ZONES_PER_REQUEST);
    const batchIds = new Set(batch.map((z) => z.id));
    const req = buildZoneNamingRequest(batch, ctx, pairs.filter(([a, b]) => batchIds.has(a.id) && batchIds.has(b.id)));
    if (Object.keys(req.questions).length === 0) continue;
    console.log(`  [cascade] naming: asking Jev about ${batch.length} zone(s), ${req.pairs.size} candidate pair(s)`);
    let response;
    try {
      response = await askJev({ state: req.state, questions: req.questions }, { taskClass: "zone.judge" });
    } catch (err) {
      if (err instanceof ClaudeClientError) {
        console.warn(`  [judge] zone naming failed (${err.reason}) — keeping algorithmic names`);
        break;
      }
      throw err;
    }
    result.calls++;
    addUsage(usage, response.tokenUsage);

    for (const [qid, { zone, candidates }] of req.naming) {
      const a = response.answers[qid];
      if (a?.type !== "choice") continue;
      if (a.choice === NONE || a.confidence < NAMING_MIN_CONFIDENCE) {
        if (ctx.skipGeneratedNames?.has(zone.id)) {
          result.skippedFallback++;
        } else {
          escalate.push(zone);
        }
        continue;
      }
      const k = Number(a.choice.slice(1));
      const chosen = candidates[k];
      if (chosen) named.set(zone.id, chosen.name);
    }
    for (const [qid, [a, b]] of req.pairs) {
      const ans = response.answers[qid];
      if (ans?.type !== "noul") continue;
      if (ans.noul >= MERGE_MIN_PROBABILITY) {
        const shared = mergeNames.get(a.id) ?? mergeNames.get(b.id) ?? `merge:${a.id}`;
        mergeNames.set(a.id, shared);
        mergeNames.set(b.id, shared);
      } else if (ans.noul >= MERGE_UNCERTAIN_BAND[0] && ans.noul <= MERGE_UNCERTAIN_BAND[1]) {
        result.findings.push({
          type: "observation",
          pass: 1,
          scope: a.id,
          text: `Zones "${a.name}" and "${b.name}" may be one architectural concept; the import graph links them but the judgment was undecided.`,
          severity: "info",
          category: "structural",
          related: [b.id],
          confidence: Math.round(ans.noul * 100) / 100,
        });
      }
    }
  }

  // Generated fallback, verified by Jev: one text-model call per chunk of
  // zones, then one Jev request per chunk carrying every zone's pick and fit
  // questions. Each zone's outcome is still independent.
  if (result.skippedFallback > 0) {
    console.log(`  [cascade] naming: ${result.skippedFallback} zone(s) keep their algorithmic name — generated names were already tried on these files`);
  }
  result.fallbackZoneIds = escalate.map((z) => z.id);
  if (ctx.deferGeneratedNames && escalate.length > 0) {
    console.log(`  [cascade] naming: ${escalate.length} zone(s) left for background name generation`);
    escalate.length = 0;
  }
  result.escalated = escalate.length;
  for (let start = 0; start < escalate.length; start += NAME_PROPOSAL_CHUNK) {
    const chunk = escalate.slice(start, start + NAME_PROPOSAL_CHUNK);
    console.log(`  [cascade] naming: generating names for ${chunk.length} zone(s) in one call (${escalate.map((z) => z.id).slice(start, start + NAME_PROPOSAL_CHUNK).join(", ")})`);
    const proposed = await proposeZoneNamesFor(chunk);
    const withNames = chunk.filter((z) => (proposed.get(z.id)?.length ?? 0) > 0);
    if (withNames.length === 0) continue;

    const state: Record<string, JsonValue> = {};
    const questions: Record<string, JevQuestion> = {};
    withNames.forEach((zone, i) => {
      const names = proposed.get(zone.id)!;
      const id = `z${i}`;
      state[id] = { files: zone.files.slice(0, ZONE_FILE_SAMPLE), entryPoints: zone.entryPoints.slice(0, 5), names };
      const criteria: Record<string, JsonValue> = {};
      names.forEach((n, k) => { criteria[`g${k}`] = n; });
      criteria[NONE] = "None of these names describes the files.";
      questions[`pick-${id}`] = choice(`Which of the proposed names in \`${id}.names\` best describes the module whose files are \`${id}.files\`?`, criteria);
      names.forEach((_, k) => {
        questions[`fits-${id}-${k}`] = noul(`Does the name \`${id}.names[${k}]\` accurately describe the files in \`${id}.files\`?`);
      });
    });
    let response;
    try {
      response = await askJev({ state, questions }, { taskClass: "zone.judge" });
    } catch (err) {
      if (err instanceof ClaudeClientError) {
        console.warn(`  [judge] generated-name verification failed (${err.reason}) — keeping algorithmic names for ${withNames.length} zone(s)`);
        continue;
      }
      throw err;
    }
    result.calls++;
    addUsage(usage, response.tokenUsage);
    withNames.forEach((zone, i) => {
      const id = `z${i}`;
      const names = proposed.get(zone.id)!;
      const pick = response.answers[`pick-${id}`];
      if (pick?.type !== "choice" || pick.choice === NONE) return;
      const k = Number(pick.choice.slice(1));
      const fits = response.answers[`fits-${id}-${k}`];
      if (fits?.type === "noul" && fits.noul >= GENERATED_NAME_MIN_PROBABILITY && names[k]) {
        named.set(zone.id, names[k]);
      }
    });
  }

  // Apply names, then merges (mergeZonesByName merges by equal name).
  let out = zones.map((z) => {
    const name = named.get(z.id);
    if (name && name !== z.name) result.renamed++;
    const mergeName = mergeNames.get(z.id);
    return {
      ...z,
      ...(name ? { name } : {}),
      ...(mergeName ? { name: mergeName } : {}),
    };
  });
  if (mergeNames.size > 0) {
    const before = out.length;
    out = mergeZonesByName(out).map((z) => {
      if (!z.name.startsWith("merge:")) return z;
      // Restore the larger member's chosen name for the merged zone.
      const members = zones.filter((m) => mergeNames.get(m.id) === z.name).sort((a, b) => b.files.length - a.files.length);
      const lead = members[0];
      return { ...z, id: lead.id, name: named.get(lead.id) ?? lead.name };
    });
    result.merged = before - out.length;
  }

  if (result.calls > 0) {
    console.log(
      `  [judge] zone naming: ${zones.length} zone(s) in ${result.calls} request(s) — ` +
        `${result.renamed} renamed, ${result.merged} merged, ${result.escalated} escalated to generated names (${usage.input} in / ${usage.output} out)`,
    );
  }
  result.zones = out;
  result.tokenUsage = result.calls > 0 ? usage : undefined;
  return result;
}
