/**
 * Merge (consolidate) multiple PRD items into one.
 *
 * Use cases:
 * - Cleaning up redundant tasks generated by `rex analyze`
 * - Combining tasks that turned out to be the same work
 * - Rolling up granular subtasks into a single task
 *
 * Rules:
 * - All source items must be siblings (same parent and same level)
 * - One source item is designated the "target" — it survives
 * - The rest are "absorbed" — their data is merged into the target,
 *   then they are removed from the tree
 * - Children of absorbed items are reparented under the target
 * - blockedBy references to absorbed items are rewritten to point to the target
 *
 * @module core/merge
 */

import type { PRDItem, ItemLevel } from "../schema/index.js";
import { findItem, removeFromTree, walkTree } from "./tree.js";

// ── Types ────────────────────────────────────────────────────────────

export interface MergeOptions {
  /** New title for the merged item. If not provided, keeps the target's title. */
  title?: string;
  /** New description for the merged item. If not provided, combines all descriptions. */
  description?: string;
}

export interface MergeValidation {
  valid: boolean;
  error?: string;
}

export interface MergePreview {
  /** The item that will survive (with merged fields applied). */
  target: {
    id: string;
    title: string;
    description?: string;
    acceptanceCriteria: string[];
    tags: string[];
    blockedBy: string[];
    childCount: number;
  };
  /** Items that will be absorbed (removed). */
  absorbed: Array<{
    id: string;
    title: string;
    level: ItemLevel;
    status: string;
    childCount: number;
  }>;
  /** IDs whose blockedBy references will be rewritten. */
  rewrittenDependencyCount: number;
}

export interface MergeResult {
  /** The surviving merged item. */
  targetId: string;
  /** IDs of items that were absorbed (removed). */
  absorbedIds: string[];
  /** IDs of children that were reparented under the target. */
  reparentedChildIds: string[];
  /** Count of blockedBy references rewritten across the tree. */
  rewrittenDependencyCount: number;
}

// ── Validation ──────────────────────────────────────────────────────

/**
 * Validate that a merge operation is structurally valid.
 *
 * Requirements:
 * 1. At least 2 source IDs
 * 2. Target must be one of the source IDs
 * 3. All source items must exist
 * 4. All source items must be at the same level
 * 5. All source items must share the same parent (siblings)
 */
export function validateMerge(
  items: PRDItem[],
  sourceIds: string[],
  targetId: string,
): MergeValidation {
  if (sourceIds.length < 2) {
    return { valid: false, error: "At least 2 items are required for a merge." };
  }

  if (!sourceIds.includes(targetId)) {
    return { valid: false, error: "Target must be one of the source items." };
  }

  // Check all items exist and collect their parents/levels
  const parentIds: Array<string | null> = [];
  const levels: ItemLevel[] = [];

  for (const id of sourceIds) {
    const entry = findItem(items, id);
    if (!entry) {
      return { valid: false, error: `Item "${id}" not found.` };
    }
    const parentId = entry.parents.length > 0
      ? entry.parents[entry.parents.length - 1].id
      : null;
    parentIds.push(parentId);
    levels.push(entry.item.level);
  }

  // All same level
  const firstLevel = levels[0];
  if (!levels.every((l) => l === firstLevel)) {
    return { valid: false, error: "All items must be at the same level to merge." };
  }

  // All same parent (siblings)
  const firstParent = parentIds[0];
  if (!parentIds.every((p) => p === firstParent)) {
    return { valid: false, error: "All items must be siblings (same parent) to merge." };
  }

  return { valid: true };
}

// ── Preview ─────────────────────────────────────────────────────────

/**
 * Build a preview of the merge result without modifying the tree.
 *
 * Call after validateMerge succeeds.
 */
export function previewMerge(
  items: PRDItem[],
  sourceIds: string[],
  targetId: string,
  options?: MergeOptions,
): MergePreview {
  const targetEntry = findItem(items, targetId)!;
  const target = targetEntry.item;
  const absorbedIds = sourceIds.filter((id) => id !== targetId);

  // Combine acceptance criteria (deduplicated)
  const allCriteria: string[] = [];
  const seenCriteria = new Set<string>();
  for (const id of [targetId, ...absorbedIds]) {
    const entry = findItem(items, id)!;
    for (const ac of entry.item.acceptanceCriteria ?? []) {
      if (!seenCriteria.has(ac)) {
        seenCriteria.add(ac);
        allCriteria.push(ac);
      }
    }
  }

  // Combine tags (deduplicated)
  const allTags = new Set<string>();
  for (const id of sourceIds) {
    const entry = findItem(items, id)!;
    for (const tag of entry.item.tags ?? []) {
      allTags.add(tag);
    }
  }

  // Combine blockedBy (deduplicated, excluding source IDs)
  const allBlockedBy = new Set<string>();
  for (const id of sourceIds) {
    const entry = findItem(items, id)!;
    for (const dep of entry.item.blockedBy ?? []) {
      if (!sourceIds.includes(dep)) {
        allBlockedBy.add(dep);
      }
    }
  }

  // Count children that will be reparented
  let reparentedChildCount = 0;
  for (const id of absorbedIds) {
    const entry = findItem(items, id)!;
    reparentedChildCount += (entry.item.children ?? []).length;
  }

  // Count blockedBy references to absorbed items across the tree
  const absorbedSet = new Set(absorbedIds);
  let rewrittenDependencyCount = 0;
  for (const { item } of walkTree(items)) {
    if (sourceIds.includes(item.id)) continue;
    if (item.blockedBy) {
      for (const dep of item.blockedBy) {
        if (absorbedSet.has(dep)) {
          rewrittenDependencyCount++;
        }
      }
    }
  }

  // Build combined description
  let combinedDescription = options?.description;
  if (combinedDescription === undefined) {
    const descriptions: string[] = [];
    for (const id of [targetId, ...absorbedIds]) {
      const entry = findItem(items, id)!;
      if (entry.item.description) {
        descriptions.push(entry.item.description);
      }
    }
    combinedDescription = descriptions.length > 0
      ? descriptions.join("\n\n---\n\n")
      : undefined;
  }

  const absorbed = absorbedIds.map((id) => {
    const entry = findItem(items, id)!;
    return {
      id: entry.item.id,
      title: entry.item.title,
      level: entry.item.level,
      status: entry.item.status,
      childCount: (entry.item.children ?? []).length,
    };
  });

  const existingTargetChildren = (target.children ?? []).length;

  return {
    target: {
      id: target.id,
      title: options?.title ?? target.title,
      description: combinedDescription,
      acceptanceCriteria: allCriteria,
      tags: [...allTags].sort(),
      blockedBy: [...allBlockedBy],
      childCount: existingTargetChildren + reparentedChildCount,
    },
    absorbed,
    rewrittenDependencyCount,
  };
}

// ── Execute ─────────────────────────────────────────────────────────

/**
 * Execute the merge: update the target, reparent children, rewrite
 * dependencies, and remove absorbed items.
 *
 * Modifies the items array in place.
 *
 * Call after validateMerge succeeds.
 */
export function mergeItems(
  items: PRDItem[],
  sourceIds: string[],
  targetId: string,
  options?: MergeOptions,
): MergeResult {
  const absorbedIds = sourceIds.filter((id) => id !== targetId);
  const absorbedSet = new Set(absorbedIds);

  const targetEntry = findItem(items, targetId)!;
  const target = targetEntry.item;

  // 1. Merge fields into target

  // Title
  if (options?.title) {
    target.title = options.title;
  }

  // Description — combine from all sources
  if (options?.description !== undefined) {
    target.description = options.description;
  } else {
    const descriptions: string[] = [];
    for (const id of [targetId, ...absorbedIds]) {
      const entry = findItem(items, id)!;
      if (entry.item.description) {
        descriptions.push(entry.item.description);
      }
    }
    if (descriptions.length > 0) {
      target.description = descriptions.join("\n\n---\n\n");
    }
  }

  // Acceptance criteria — deduplicated union
  const allCriteria: string[] = [];
  const seenCriteria = new Set<string>();
  for (const id of [targetId, ...absorbedIds]) {
    const entry = findItem(items, id)!;
    for (const ac of entry.item.acceptanceCriteria ?? []) {
      if (!seenCriteria.has(ac)) {
        seenCriteria.add(ac);
        allCriteria.push(ac);
      }
    }
  }
  if (allCriteria.length > 0) {
    target.acceptanceCriteria = allCriteria;
  }

  // Tags — deduplicated union
  const allTags = new Set<string>();
  for (const id of sourceIds) {
    const entry = findItem(items, id)!;
    for (const tag of entry.item.tags ?? []) {
      allTags.add(tag);
    }
  }
  if (allTags.size > 0) {
    target.tags = [...allTags].sort();
  }

  // BlockedBy — union excluding self-references and source IDs
  const allBlockedBy = new Set<string>();
  for (const id of sourceIds) {
    const entry = findItem(items, id)!;
    for (const dep of entry.item.blockedBy ?? []) {
      if (!sourceIds.includes(dep)) {
        allBlockedBy.add(dep);
      }
    }
  }
  if (allBlockedBy.size > 0) {
    target.blockedBy = [...allBlockedBy];
  } else {
    delete target.blockedBy;
  }

  // 2. Reparent children of absorbed items under the target
  const reparentedChildIds: string[] = [];
  if (!target.children) {
    target.children = [];
  }

  for (const id of absorbedIds) {
    const entry = findItem(items, id)!;
    const children = entry.item.children ?? [];
    for (const child of children) {
      reparentedChildIds.push(child.id);
    }
    // Move children to target (splice them out and into target)
    target.children.push(...children);
    entry.item.children = [];
  }

  // 3. Rewrite blockedBy references across the entire tree
  let rewrittenDependencyCount = 0;
  for (const { item } of walkTree(items)) {
    if (item.blockedBy && item.blockedBy.length > 0) {
      let changed = false;
      const newBlockedBy: string[] = [];
      const seen = new Set<string>();
      for (const dep of item.blockedBy) {
        const resolved = absorbedSet.has(dep) ? targetId : dep;
        if (dep !== resolved) {
          changed = true;
          rewrittenDependencyCount++;
        }
        if (!seen.has(resolved)) {
          seen.add(resolved);
          newBlockedBy.push(resolved);
        }
      }
      if (changed) {
        item.blockedBy = newBlockedBy;
      }
    }
  }

  // 4. Remove absorbed items from the tree
  for (const id of absorbedIds) {
    removeFromTree(items, id);
  }

  return {
    targetId,
    absorbedIds,
    reparentedChildIds,
    rewrittenDependencyCount,
  };
}
