/**
 * Code-owner files from the product layer's stewards.
 *
 * Stewards are plain strings (`Steward` in `schema/v2.ts`): a git email, or a
 * GitHub-style handle (`@org/team`). The root product header's list is the
 * default; an area's own `stewards` replaces it for that area's folder. One
 * rule is written per area (its folder, or its `<slug>.md` while it has no
 * children), so no rule matches the root header, the
 * root `state.yaml`, or anything under `changes/`: a change that only touches
 * those asks nobody for review.
 *
 * Emails go in both files. A handle is GitHub syntax, so the Bitbucket file
 * omits it and the plan carries a warning naming it.
 *
 * Pure: reads nothing and writes nothing. The command applies the plan.
 *
 * @module rex/codeowners/plan
 */

import type { RuleNode } from "../schema/v2-rules.js";

export type CodeOwnerHost = "github" | "bitbucket";

/** Where each host reads its code-owner file, relative to the repository root. */
export const CODE_OWNER_FILES: Readonly<Record<CodeOwnerHost, string>> = {
  github: "CODEOWNERS",
  bitbucket: ".bitbucket/CODEOWNERS",
};

export interface CodeOwnerFile {
  host: CodeOwnerHost;
  /** Repository-relative, forward slashes. */
  path: string;
  content: string;
}

export interface CodeOwnerPlan {
  files: CodeOwnerFile[];
  warnings: string[];
}

export interface CodeOwnerInput {
  /** The root header's `stewards`: the default for every area. */
  defaultStewards?: unknown;
  /** The product layer's root nodes. */
  product: readonly RuleNode[];
  /** The product directory relative to the repository root, forward slashes (e.g. `.rex/product`). */
  productDir: string;
}

const EMAIL = /^[^\s@]+@[^\s@]+$/;
const HANDLE = /^@\S+$/;

function stewardList(value: unknown): string[] | undefined {
  return Array.isArray(value)
    ? value.filter((s): s is string => typeof s === "string").map((s) => s.trim())
    : undefined;
}

interface AreaEntry {
  /** CODEOWNERS pattern: `/<folder>/` for an area with children, `/<file>.md` for a leaf area. */
  path: string;
  title: string;
  stewards: string[];
}

function collectAreas(nodes: readonly RuleNode[], dir: string, fallback: string[], out: AreaEntry[]): void {
  for (const node of nodes) {
    if (node.status === "deleted") continue;
    const path = dir + "/" + node.slug;
    if (node.type === "area") {
      // The tree writer stores a node without children as `<slug>.md`, not a folder (prd-model-writer isFolderNode).
      const pattern = "/" + path + ((node.children?.length ?? 0) > 0 ? "/" : ".md");
      out.push({ path: pattern, title: node.title, stewards: stewardList(node.stewards) ?? fallback });
    }
    if (node.children?.length) collectAreas(node.children, path, fallback, out);
  }
}

const HEADER =
  "# Generated by `rex codeowners` from the product layer's stewards. Edit the stewards, not this file.";

function render(
  host: CodeOwnerHost,
  areas: readonly AreaEntry[],
  warnings: string[],
  omitted: Map<string, string[]>,
): string {
  const lines = [HEADER];
  const emitted: string[] = [];
  for (const area of areas) {
    const owners: string[] = [];
    for (const raw of area.stewards) {
      if (EMAIL.test(raw)) owners.push(raw);
      else if (HANDLE.test(raw)) {
        if (host === "github") owners.push(raw);
        else omitted.set(raw, [...(omitted.get(raw) ?? []), area.title]);
      } else if (host === "github") {
        warnings.push(
          `Steward "${raw}" of area "${area.title}" is neither an email nor an @handle; left out of both files.`,
        );
      }
    }
    const rule = area.path;
    const unique = [...new Set(owners)];
    // An ownerless rule matters only where it cancels an enclosing area's rule.
    if (unique.length === 0 && !emitted.some((p) => p.endsWith("/") && rule.startsWith(p))) continue;
    emitted.push(rule);
    lines.push(unique.length ? rule + " " + unique.join(" ") : rule);
  }
  return lines.join("\n") + "\n";
}

/** Plan both code-owner files from one stewards list. Areas are written parents first: the last matching rule wins. */
export function planCodeOwners(input: CodeOwnerInput): CodeOwnerPlan {
  const areas: AreaEntry[] = [];
  collectAreas(input.product, input.productDir.replace(/^\/+|\/+$/g, ""), stewardList(input.defaultStewards) ?? [], areas);

  const warnings: string[] = [];
  const omitted = new Map<string, string[]>();
  const files = (Object.keys(CODE_OWNER_FILES) as CodeOwnerHost[]).map((host) => ({
    host,
    path: CODE_OWNER_FILES[host],
    content: render(host, areas, warnings, omitted),
  }));
  for (const [handle, titles] of omitted) {
    warnings.push(
      handle + " is a GitHub handle: omitted from " + CODE_OWNER_FILES.bitbucket +
        " (areas: " + [...new Set(titles)].join(", ") + ").",
    );
  }
  return { files, warnings };
}
