/**
 * Tailing a hench run: its terminal log and its structured progress events.
 *
 * Hench writes two files while a run is in progress (see hench's
 * `store/run-log.ts` and `store/run-events.ts`) and records their absolute
 * paths on the run record as `logPath` and `eventsPath`. This module turns a
 * run record into confined file paths, reads either file from a cursor, and
 * announces appended content to sockets for runs someone is watching.
 *
 * ## Path confinement
 *
 * The paths come from a JSON file on disk, so they are input, not trust. A
 * file is served only if — after resolving symlinks — it lies inside
 * `.run-logs/` or `<hench dir>/runs/` of a worktree `git worktree list`
 * reports for the served repository. Anything else is answered exactly like a
 * missing file, so the response does not reveal whether a path exists.
 *
 * ## Cursors
 *
 * - Log: a byte offset. A response never ends mid-way through a UTF-8
 *   character — the incomplete tail is left for the next read — so
 *   concatenating responses reproduces the file exactly.
 * - Events: a 1-based line number. Only newline-terminated lines count; a
 *   line the writer has not finished is invisible until it is.
 *
 * ## "Watching"
 *
 * The socket protocol has no client→server messages, so a client watches a
 * run by tailing it: every tail request for a running run takes a lease of
 * {@link RUN_TAIL_LEASE_MS} on it, and while any lease is held a poller stats
 * the run's files every {@link RUN_TAIL_POLL_MS} and broadcasts a
 * `hench:run-appended` frame when one grows. The frame only announces; the
 * client fetches the content with its cursor. A client that wants frames to
 * keep coming through a quiet stretch re-tails before the lease runs out.
 *
 * @module web/server/run-tail
 */

import { closeSync, openSync, readFileSync, readSync, readdirSync, realpathSync, statSync } from "node:fs";
import { isAbsolute, join, relative } from "node:path";
import { resolveLayout } from "@n-dx/llm-client";
import type { WebSocketBroadcaster } from "./websocket.js";

/** Poll interval for watched runs — keeps a frame within ~¼ s of a write. */
export const RUN_TAIL_POLL_MS = 250;

/** How long one tail request keeps a run watched. */
export const RUN_TAIL_LEASE_MS = 60_000;

/** Largest log slice one response carries; follow `next` for the rest. */
export const MAX_LOG_CHUNK_BYTES = 2 * 1024 * 1024;

/** Most events one response carries; follow `next` for the rest. */
export const MAX_EVENTS_PER_RESPONSE = 1000;

/** Where hench writes run logs: the project root, not the hench dir (hench `store/run-log.ts`). */
const RUN_LOGS_DIRNAME = ".run-logs";

/** Run ids are generated by hench; anything else is not a run id. */
const RUN_ID_PATTERN = /^[A-Za-z0-9._-]+$/;

export function isValidRunId(runId: string): boolean {
  return RUN_ID_PATTERN.test(runId) && runId !== "." && runId !== "..";
}

// ── Confinement ─────────────────────────────────────────────────────────────

/** realpath, or null when the path does not exist. */
function realpathOrNull(path: string): string | null {
  try {
    return realpathSync.native(path);
  } catch {
    return null;
  }
}

/**
 * Directories of one worktree that tail routes may read from. The hench dir
 * comes from the layout resolver: `.hench/` in the legacy layout, the `.ndx/`
 * container's hench entry otherwise.
 */
export function allowedTailDirs(worktreeRoot: string): string[] {
  return [join(worktreeRoot, RUN_LOGS_DIRNAME), join(resolveLayout(worktreeRoot).henchDir, "runs")];
}

function isInside(dir: string, path: string): boolean {
  const rel = relative(dir, path);
  return rel.length > 0 && !rel.startsWith("..") && !isAbsolute(rel);
}

/**
 * The real path of `path` if it is a regular file inside an allowed directory
 * of one of `worktreeRoots`, else null.
 */
export function confineTailPath(path: unknown, worktreeRoots: readonly string[]): string | null {
  if (typeof path !== "string" || !isAbsolute(path)) return null;
  const real = realpathOrNull(path);
  if (!real) return null;
  try {
    if (!statSync(real).isFile()) return null;
  } catch {
    return null;
  }
  for (const root of worktreeRoots) {
    for (const dir of allowedTailDirs(root)) {
      const realDir = realpathOrNull(dir);
      if (realDir && isInside(realDir, real)) return real;
    }
  }
  return null;
}

// ── Locating a run's files ──────────────────────────────────────────────────

/** A run record and where it was found. */
export interface LocatedRun {
  run: Record<string, unknown>;
  /** The runs directory holding the record. */
  runsDir: string;
  /** Root of the worktree the run belongs to — always one of the registered roots. */
  worktreeRoot: string;
}

/** The run's log file, and whether it is the incremental log or an older end-of-run one. */
export interface TailLogFile {
  path: string;
  source: "incremental" | "final";
}

/**
 * The run's log, confined.
 *
 * A recorded `logPath` is the only candidate when present — if it is refused,
 * so is the request; nothing is guessed in its place. Without one (a run
 * recorded before the incremental log), the end-of-run log is found by its
 * `<timestamp>-<runId>.log` name in the run's worktree's `.run-logs/`.
 */
export function resolveRunLogFile(located: LocatedRun, worktreeRoots: readonly string[]): TailLogFile | null {
  const { run, worktreeRoot } = located;
  if (run.logPath !== undefined) {
    const path = confineTailPath(run.logPath, worktreeRoots);
    return path ? { path, source: "incremental" } : null;
  }
  const id = run.id;
  if (typeof id !== "string" || !isValidRunId(id)) return null;
  const dir = join(worktreeRoot, RUN_LOGS_DIRNAME);
  let names: string[];
  try {
    names = readdirSync(dir);
  } catch {
    return null;
  }
  // Newest first if a run id ever appears twice (a re-run reusing an id).
  const match = names.filter((name) => name.endsWith(`-${id}.log`)).sort().pop();
  if (!match) return null;
  const path = confineTailPath(join(dir, match), worktreeRoots);
  return path ? { path, source: "final" } : null;
}

/** Outcome of resolving the run's events file. */
export type TailEventsFile =
  | { kind: "file"; path: string }
  /** The run has no event stream (recorded before it existed). Not an error. */
  | { kind: "absent" }
  /** A recorded path was refused. */
  | { kind: "refused" };

/**
 * The run's event stream, confined. A recorded `eventsPath` is the only
 * candidate when present; without one, `<runId>.events.jsonl` beside the record.
 */
export function resolveRunEventsFile(located: LocatedRun, worktreeRoots: readonly string[]): TailEventsFile {
  const { run, runsDir } = located;
  if (run.eventsPath !== undefined) {
    const path = confineTailPath(run.eventsPath, worktreeRoots);
    return path ? { kind: "file", path } : { kind: "refused" };
  }
  const id = run.id;
  if (typeof id !== "string" || !isValidRunId(id)) return { kind: "absent" };
  const path = confineTailPath(join(runsDir, `${id}.events.jsonl`), worktreeRoots);
  return path ? { kind: "file", path } : { kind: "absent" };
}

// ── Reading from a cursor ───────────────────────────────────────────────────

/**
 * Length of the longest prefix of `buf` that does not end inside a UTF-8
 * multi-byte sequence. Only the last three bytes can belong to an unfinished
 * sequence, so only they are inspected.
 */
export function utf8CompletePrefixLength(buf: Buffer): number {
  const len = buf.length;
  for (let back = 1; back <= Math.min(3, len); back++) {
    const byte = buf[len - back]!;
    if ((byte & 0xc0) === 0x80) continue; // continuation byte — keep looking for the lead
    const need = byte >= 0xf0 ? 4 : byte >= 0xe0 ? 3 : byte >= 0xc0 ? 2 : 1;
    return need > back ? len - back : len;
  }
  return len;
}

export interface LogChunk {
  content: string;
  /** Offset the content starts at (0 after a reset). */
  from: number;
  /** Cursor for the next request. */
  next: number;
  /** File size when read. */
  size: number;
  /** The requested cursor was past the end of the file, so reading restarted at 0. */
  reset: boolean;
}

/** Read up to `maxBytes` of the log starting at byte `from`. */
export function readLogChunk(path: string, from: number, maxBytes = MAX_LOG_CHUNK_BYTES): LogChunk {
  const fd = openSync(path, "r");
  try {
    const size = statSync(path).size;
    const reset = from > size;
    const start = reset ? 0 : from;
    const length = Math.min(maxBytes, size - start);
    const buf = Buffer.alloc(length);
    const read = length > 0 ? readSync(fd, buf, 0, length, start) : 0;
    const complete = utf8CompletePrefixLength(buf.subarray(0, read));
    return {
      content: buf.subarray(0, complete).toString("utf-8"),
      from: start,
      next: start + complete,
      size,
      reset,
    };
  } finally {
    closeSync(fd);
  }
}

export interface EventsChunk {
  /** Each event as written, plus its 1-based line number as `seq`. */
  events: Array<Record<string, unknown> & { seq: number }>;
  /** Cursor for the next request: the last seq included (or `after` if none). */
  next: number;
  /** Complete lines in the file when read. */
  total: number;
}

/**
 * Events after line `after`. A line that is not valid JSON keeps its seq —
 * so cursors stay stable — but is not returned.
 */
export function readEventsAfter(path: string, after: number, max = MAX_EVENTS_PER_RESPONSE): EventsChunk {
  const text = readFileSync(path, "utf-8");
  const lastNewline = text.lastIndexOf("\n");
  const lines = lastNewline === -1 ? [] : text.slice(0, lastNewline).split("\n");
  const events: EventsChunk["events"] = [];
  let next = Math.min(after, lines.length);
  for (let i = next; i < lines.length && events.length < max; i++) {
    next = i + 1;
    try {
      const parsed: unknown = JSON.parse(lines[i]!);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        events.push({ ...(parsed as Record<string, unknown>), seq: i + 1 });
      }
    } catch {
      // Not JSON: the seq is spent, the line is skipped. See the doc comment.
    }
  }
  return { events, next, total: lines.length };
}

/** How much of an events file's end {@link readLastEvent} reads. */
const LAST_EVENT_WINDOW_BYTES = 16 * 1024;

/**
 * The last complete, parseable event in the file, or null. Reads only the
 * file's last {@link LAST_EVENT_WINDOW_BYTES}, so its cost does not grow
 * with the run — the Live overview asks this of every running run.
 */
export function readLastEvent(path: string): Record<string, unknown> | null {
  let fd: number;
  try {
    fd = openSync(path, "r");
  } catch {
    return null;
  }
  try {
    const size = statSync(path).size;
    const length = Math.min(size, LAST_EVENT_WINDOW_BYTES);
    const buf = Buffer.alloc(length);
    const read = length > 0 ? readSync(fd, buf, 0, length, size - length) : 0;
    const text = buf.subarray(0, read).toString("utf-8");
    // Only newline-terminated lines are events; the first line of the window
    // may be a fragment and fails to parse, which is fine — it is the oldest.
    const lines = text.slice(0, text.lastIndexOf("\n") + 1).split("\n");
    for (let i = lines.length - 1; i >= 0; i--) {
      const line = lines[i]!.trim();
      if (!line) continue;
      try {
        const parsed: unknown = JSON.parse(line);
        if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) return parsed as Record<string, unknown>;
      } catch {
        // A torn or malformed line: keep looking further back.
      }
    }
    return null;
  } finally {
    closeSync(fd);
  }
}

// ── Watching ────────────────────────────────────────────────────────────────

/** Frame announcing that a watched run's log or event stream grew. */
export interface RunAppendedFrame {
  type: "hench:run-appended";
  runId: string;
  stream: "log" | "events";
  /** File size in bytes after the append. */
  size: number;
  timestamp: string;
}

interface RunTailWatch {
  runId: string;
  files: Partial<Record<RunAppendedFrame["stream"], { path: string; size: number }>>;
  broadcast: WebSocketBroadcaster;
  expiresAt: number;
}

export interface WatchRunTailOptions {
  /** Identifies the watch: one per (workspace of the requester, run). */
  key: string;
  runId: string;
  logPath?: string | null;
  eventsPath?: string | null;
  /** Already tagged with the requester's workspace. */
  broadcast: WebSocketBroadcaster;
}

const watches = new Map<string, RunTailWatch>();
let pollTimer: ReturnType<typeof setInterval> | null = null;

function fileSize(path: string): number | null {
  try {
    return statSync(path).size;
  } catch {
    return null;
  }
}

/**
 * Watch a run's files (or renew the lease on an existing watch). Sizes seen
 * now are the baseline: only growth after this call is announced, since the
 * caller has just served what was there.
 */
export function watchRunTail(options: WatchRunTailOptions): void {
  const expiresAt = Date.now() + RUN_TAIL_LEASE_MS;
  const existing = watches.get(options.key);
  const watch: RunTailWatch = existing ?? { runId: options.runId, files: {}, broadcast: options.broadcast, expiresAt };
  watch.broadcast = options.broadcast;
  watch.expiresAt = expiresAt;
  const add = (stream: RunAppendedFrame["stream"], path: string | null | undefined): void => {
    if (!path || watch.files[stream]?.path === path) return;
    watch.files[stream] = { path, size: fileSize(path) ?? 0 };
  };
  add("log", options.logPath);
  add("events", options.eventsPath);
  watches.set(options.key, watch);
  if (!pollTimer) {
    pollTimer = setInterval(pollWatches, RUN_TAIL_POLL_MS);
    pollTimer.unref();
  }
}

function pollWatches(): void {
  const now = Date.now();
  for (const [key, watch] of watches) {
    if (now >= watch.expiresAt) {
      watches.delete(key);
      continue;
    }
    for (const stream of ["log", "events"] as const) {
      const file = watch.files[stream];
      if (!file) continue;
      const size = fileSize(file.path);
      if (size === null || size === file.size) continue;
      // A shrink (rewritten file) is announced too: the client's cursor is stale.
      file.size = size;
      const frame: RunAppendedFrame = {
        type: "hench:run-appended",
        runId: watch.runId,
        stream,
        size,
        timestamp: new Date().toISOString(),
      };
      watch.broadcast(frame);
    }
  }
  if (watches.size === 0) stopPolling();
}

function stopPolling(): void {
  if (pollTimer) clearInterval(pollTimer);
  pollTimer = null;
}

/** Number of runs currently watched (lease held). */
export function runTailWatchCount(): number {
  return watches.size;
}

/** Drop every watch. Called on server shutdown and by tests. */
export function stopRunTailWatches(): void {
  watches.clear();
  stopPolling();
}
