/**
 * `sv narrate <dir>` — narrate the zones the cascade left for later.
 *
 * `analyze` writes its judged results and returns; when zones were escalated
 * it records them on `manifest.narration` and spawns this command detached.
 * Here they are narrated in one text-model call (enrich-multiplex.ts), the
 * findings are judged like any other, and insights and findings are merged
 * into zones.json. `analyze --wait` runs the same function inline.
 *
 * Staleness: a second `analyze` may finish while this runs. The manifest's
 * `analyzedAt` is read at the start and again before writing; if it moved,
 * the result is dropped — the newer analysis has already scheduled its own.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import type { Finding, Manifest, NarrationState, Zone, Zones } from "../../schema/index.js";
import { DATA_FILES, readManifest, writeManifest, toCanonicalJSON, deduplicateFindings, enforceSeverityRules } from "../sourcevision-core.js";
import { SV_DIR } from "./constants.js";
import { narrateZones } from "../../analyzers/enrich-multiplex.js";
import { nameZonesBySelection } from "../../analyzers/zone-naming.js";
import { routeLayoutFor } from "../../analyzers/route-convention.js";
import { dedupeZoneNames } from "../../analyzers/enrich-cascade.js";
import { judgeFindings } from "../../analyzers/enrich-judge.js";
import { buildProjectProfile } from "../../analyzers/project-profile.js";
import { startRunLedger, snapshotRunLedger, formatRunLedger } from "../../analyzers/run-ledger.js";
import { loadHints, loadFileArchetypes } from "./analyze-phases.js";
import type { AnalyzeContext } from "./analyze-phases.js";
import { emptyAnalyzeTokenUsage } from "../../analyzers/token-usage.js";
import { info } from "../output.js";
import { dim, bold, warn } from "@n-dx/llm-client";

/** Relative to the project root; the detached narrator's stdio goes here. */
export const NARRATION_LOG = `${SV_DIR}/.cache/narration.log`;

/**
 * The pieces of `analyze` the narrator reuses. Injected rather than imported
 * so the import direction stays `analyze → narrate` (analyze schedules or
 * inlines narration; narration never reaches back into analyze).
 */
export interface NarrateDeps {
  /** Loads LLM config, sets project dir and judgment cache, prints the vendor header. */
  bootstrap: (absDir: string) => Promise<unknown>;
  /** Regenerates llms.txt / CONTEXT.md / zone outputs from the data files. */
  generateOutputs: (ctx: AnalyzeContext) => Promise<void>;
  /** Appends one run record to `.sourcevision/.cache/analyses.jsonl`. */
  appendHistory: (svDir: string, line: string) => void;
}

export interface NarrateOptions {
  /** Called from `analyze --wait`: the LLM config and ledger are already set up and outputs are generated by the caller. */
  inline?: boolean;
  /** Zone ids to narrate; defaults to `manifest.narration.zones`. */
  zoneIds?: string[];
  /** Zone ids whose generated names are still to be produced; defaults to `manifest.narration.names`. */
  nameZoneIds?: string[];
  deps: NarrateDeps;
}

/**
 * Apply generated names to the stored zones, keeping every name unique.
 * Pure, for the same reason as {@link mergeNarration}.
 */
export function applyGeneratedNames(stored: Zones, named: Zone[]): { zones: Zones; renamed: string[] } {
  const byId = new Map(named.map((z) => [z.id, z.name]));
  const renamed: string[] = [];
  const zones = stored.zones.map((z) => {
    const name = byId.get(z.id);
    if (!name || name === z.name) return z;
    renamed.push(z.id);
    return { ...z, name };
  });
  return { zones: { ...stored, zones: dedupeZoneNames(zones) }, renamed };
}

export interface NarrationMerge {
  zones: Zones;
  narratedIds: string[];
  newFindings: number;
}

/**
 * Merge narrated zones and judged findings into the stored zones document.
 * Pure, so it can be tested without a model: narrated zones replace their
 * stored counterparts' insights and structure hash; findings are
 * deduplicated against the existing ones and severity rules run last.
 */
export function mergeNarration(
  stored: Zones,
  narrated: Zone[],
  judgedFindings: Finding[],
): NarrationMerge {
  const byId = new Map(narrated.map((z) => [z.id, z]));
  const zones = stored.zones.map((z) => {
    const n = byId.get(z.id);
    return n ? { ...z, insights: n.insights, structureHash: n.structureHash } : z;
  });
  const findings = enforceSeverityRules(deduplicateFindings([...(stored.findings ?? []), ...judgedFindings]));
  return {
    zones: { ...stored, zones, findings: findings.length > 0 ? findings : undefined },
    narratedIds: narrated.map((z) => z.id),
    newFindings: judgedFindings.length,
  };
}

/** Reasons a narration is worth retrying on the next analyze; a failed narration call is not. */
const RETRYABLE_NARRATION_REASONS = [
  "superseded by a newer analysis",
  "narrator exited without finishing",
  "could not spawn narrator",
];

export interface NarrationTakeover {
  /** Zone ids still awaiting narration. */
  zones: string[];
  /** Zone ids still awaiting generated names. */
  names: string[];
  /** Pid of a live narrator this call stopped. */
  stopped?: number;
}

function pidAlive(pid: number): boolean {
  try {
    process.kill(pid, 0);
    return true;
  } catch (err) {
    // EPERM: the process exists but belongs to someone else.
    return (err as NodeJS.ErrnoException).code === "EPERM";
  }
}

/**
 * Called at the start of `analyze`: take over whatever the previous narrator
 * left unfinished. A live narrator is stopped — it would otherwise race this
 * analysis for zones.json and then discard its own result as superseded — and
 * a pending one whose process is gone is recorded as failed. Either way its
 * zones and names come back so this analysis can queue them again; nothing a
 * narrator was asked to do is lost to a second analyze.
 */
export function takeOverNarration(
  absDir: string,
  deps: { isAlive?: (pid: number) => boolean; kill?: (pid: number) => void } = {},
): NarrationTakeover {
  const manifest = readManifest(absDir);
  const n = manifest.narration;
  if (!n || n.status === "done") return { zones: [], names: [] };
  const isAlive = deps.isAlive ?? pidAlive;
  const kill = deps.kill ?? ((pid: number) => { try { process.kill(pid, "SIGTERM"); } catch { /* gone already */ } });

  let stopped: number | undefined;
  if (n.status === "pending") {
    let reason = "narrator exited without finishing";
    if (n.pid !== undefined && isAlive(n.pid)) {
      kill(n.pid);
      stopped = n.pid;
      reason = "superseded by a newer analysis";
    }
    manifest.narration = { ...n, status: "failed", finishedAt: new Date().toISOString(), reason };
    writeManifest(absDir, manifest);
  } else if (!RETRYABLE_NARRATION_REASONS.some((r) => n.reason?.startsWith(r))) {
    return { zones: [], names: [] };
  }
  return { zones: [...n.zones], names: [...(n.names ?? [])], ...(stopped !== undefined ? { stopped } : {}) };
}

/**
 * Fold taken-over work into this run's pending sets, keeping only zone ids
 * that still exist. Returns the merged sets and how many carried ids were
 * dropped because their zone is gone.
 */
export function carryNarration(
  carried: NarrationTakeover,
  pending: { zones?: string[]; names?: string[] },
  currentZoneIds: ReadonlySet<string>,
): { zones: string[]; names: string[]; carried: number; dropped: number } {
  const zones = new Set(pending.zones ?? []);
  const names = new Set(pending.names ?? []);
  let carriedCount = 0;
  let dropped = 0;
  for (const [from, into] of [[carried.zones, zones], [carried.names, names]] as const) {
    for (const id of from) {
      if (!currentZoneIds.has(id)) { dropped++; continue; }
      if (!into.has(id)) { into.add(id); carriedCount++; }
    }
  }
  return { zones: [...zones], names: [...names], carried: carriedCount, dropped };
}

/** True when another analysis finished after this narration began. */
export function isSuperseded(startedAnalyzedAt: string | undefined, current: Manifest): boolean {
  return startedAnalyzedAt !== undefined && current.analyzedAt !== startedAnalyzedAt;
}

function setNarration(absDir: string, patch: Partial<NarrationState>): void {
  const manifest = readManifest(absDir);
  const prev = manifest.narration ?? { status: "pending" as const, zones: [], startedAt: new Date().toISOString() };
  manifest.narration = { ...prev, ...patch };
  writeManifest(absDir, manifest);
}

export async function cmdNarrate(targetDir: string, opts: NarrateOptions): Promise<void> {
  const absDir = resolve(targetDir);
  const svDir = join(absDir, SV_DIR);
  const manifestPath = join(svDir, DATA_FILES.manifest);
  if (!existsSync(manifestPath) || !existsSync(join(svDir, DATA_FILES.zones))) {
    warn(`  [narrate] nothing to narrate — run 'sv analyze' first (${dim(svDir)})`);
    return;
  }

  if (!opts.inline) {
    await opts.deps.bootstrap(absDir);
    startRunLedger("narration");
  }

  const manifestAtStart = readManifest(absDir);
  const startedAnalyzedAt = manifestAtStart.analyzedAt;
  const zoneIds = opts.zoneIds ?? manifestAtStart.narration?.zones ?? [];
  const nameZoneIds = opts.nameZoneIds ?? manifestAtStart.narration?.names ?? [];
  if (zoneIds.length === 0 && nameZoneIds.length === 0) {
    info(`  ${dim("[narrate]")} nothing pending`);
    return;
  }

  let stored: Zones = JSON.parse(readFileSync(join(svDir, DATA_FILES.zones), "utf-8"));
  const inventory = JSON.parse(readFileSync(join(svDir, DATA_FILES.inventory), "utf-8"));
  const imports = JSON.parse(readFileSync(join(svDir, DATA_FILES.imports), "utf-8"));
  const projectProfile = buildProjectProfile(absDir, inventory, imports);
  const fileArchetypes = loadFileArchetypes(svDir);
  const hints = loadHints(svDir);

  // Names first: one proposal call for every deferred zone, verified by Jev.
  const nameTargets = stored.zones.filter((z) => nameZoneIds.includes(z.id));
  if (nameTargets.length > 0) {
    info(`${bold("[narrate]")} generating names for ${nameTargets.length} zone(s): ${nameTargets.map((z) => z.id).join(", ")}`);
    const naming = await nameZonesBySelection(nameTargets, {
      projectDir: absDir,
      fileArchetypes,
      crossings: stored.crossings,
      routeLayout: routeLayoutFor(inventory.files.map((f: { path: string }) => f.path)),
    });
    const applied = applyGeneratedNames(stored, naming.zones);
    if (applied.renamed.length > 0) {
      if (isSuperseded(startedAnalyzedAt, readManifest(absDir))) {
        setNarration(absDir, { status: "failed", finishedAt: new Date().toISOString(), reason: "superseded by a newer analysis" });
        warn("  [narrate] a newer analysis finished meanwhile — result dropped");
        return;
      }
      stored = applied.zones;
      writeFileSync(join(svDir, DATA_FILES.zones), toCanonicalJSON(stored));
      info(`  ${applied.renamed.length} zone(s) renamed → ${dim(join(svDir, DATA_FILES.zones))}`);
    }
    // Names are done: a later takeover must not queue them again.
    if (!opts.inline) setNarration(absDir, { names: [] });
  }

  const targets = stored.zones.filter((z) => zoneIds.includes(z.id));
  if (targets.length === 0) {
    if (zoneIds.length > 0) {
      warn(`  [narrate] none of the ${zoneIds.length} pending zone(s) exist in zones.json — dropped`);
    }
    if (!opts.inline) {
      const ctx: AnalyzeContext = {
        absDir, svDir, fullMode: false, fastMode: false, narrate: false, wait: true,
        tokenUsage: emptyAnalyzeTokenUsage(), inventoryResult: null,
      };
      await opts.deps.generateOutputs(ctx);
    }
    setNarration(absDir, { status: zoneIds.length > 0 ? "failed" : "done", finishedAt: new Date().toISOString(), ...(zoneIds.length > 0 ? { reason: "pending zone ids no longer exist" } : {}) });
    return;
  }

  info(`${bold("[narrate]")} ${targets.length} zone(s): ${targets.map((z) => z.id).join(", ")}`);
  const narrated = await narrateZones(targets, {
    allZones: stored.zones,
    crossings: stored.crossings,
    fileArchetypes,
    hints,
    projectProfile,
  });
  if (!narrated.success) {
    setNarration(absDir, { status: "failed", finishedAt: new Date().toISOString(), reason: "narration call failed or returned nothing parsable" });
    warn("  [narrate] failed — zones keep their judged names and descriptions");
    return;
  }

  const judged = await judgeFindings(narrated.newFindings, {
    zones: stored.zones,
    crossings: stored.crossings,
    heuristics: (stored.findings ?? []).filter((f) => f.pass === 0),
    projectDir: absDir,
  });

  if (isSuperseded(startedAnalyzedAt, readManifest(absDir))) {
    setNarration(absDir, { status: "failed", finishedAt: new Date().toISOString(), reason: "superseded by a newer analysis" });
    warn("  [narrate] a newer analysis finished meanwhile — result dropped");
    return;
  }

  const merged = mergeNarration(stored, narrated.zones, judged.findings);
  writeFileSync(join(svDir, DATA_FILES.zones), toCanonicalJSON(merged.zones));
  info(`  ${merged.narratedIds.length} zone(s) narrated, ${merged.newFindings} finding(s) judged and merged → ${dim(join(svDir, DATA_FILES.zones))}`);

  if (!opts.inline) {
    const ctx: AnalyzeContext = {
      absDir, svDir, fullMode: false, fastMode: false, narrate: false, wait: true,
      tokenUsage: emptyAnalyzeTokenUsage(), inventoryResult: null,
    };
    await opts.deps.generateOutputs(ctx);
  }

  setNarration(absDir, { status: "done", finishedAt: new Date().toISOString(), zones: merged.narratedIds });
  if (!opts.inline) {
    const run = snapshotRunLedger();
    for (const line of formatRunLedger(run)) info(dim(line));
    opts.deps.appendHistory(svDir, JSON.stringify(run));
  }
}
